---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyperjob-web
    volumes:
      - static_files:/app/static
    env_file:
      - ./ENV/.env.app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./ENV/.env.db

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - static_files:/app/static/:ro
    env_file:
      - ./ENV/.env.nginx
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
