---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hyperjob-web-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:ro
    env_file:
      - ./.env.example
    environment:
      - DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.example
    ports:
      - "5432:5432"

volumes:
  postgres_data:
