---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hyperjob-web-dev
    volumes:
      - .:/app
    env_file:
      - ./ENV/.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./ENV/.env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
